name: CI/

on:
#  workflow_dispatch:
  push:
    branches: ["main"]
    
jobs:
  CI: 
    runs-on: windows
    
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Autenticar no dokcer hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Contruindo imagem Docker
        uses: docker/build-push-action@v4.0.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            nilozjr/conversor-temp-2023:${{github.run_number}}
            nilozjr/conversor-temp-2023:latest
      - name: Upload do artefato
        uses: actions/upload-artifact@v3.1.2
        with:
          name: src
          path: ./src/*
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: src
          path: C:\Users\Olin\src
      - name: discord-webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: https://discord.com/channels/@me
          content: "Test"
  CD: 
    runs-on: windows
    needs: CI
    environment:
      name: homol
      url: 'http://localhost:8080'
    steps:
      - name: deploy
        run: |
          cd C:\Users\Olin\src
          docker compose down
          docker compose up -d     
